version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - localnetwork
    command: yarn run start
networks:
  localnetwork:
    external: true
